services:
  mlflow:
    image: python:3.11-slim
    working_dir: /mlflow
    restart: always
    volumes:
      - ./mlruns:/mlflow/mlruns
    ports:
      - "5000:5000"
    command: >
      bash -c "pip install --no-cache-dir mlflow && 
      mlflow server --host 0.0.0.0 --port 5000 
      --backend-store-uri /mlflow/mlruns 
      --default-artifact-root /mlflow/mlruns"

  api:
    image: ton_pseudo_docker/le_nom_que_tu_veux:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - USE_MLFLOW_REGISTRY=false
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - mlflow
